server.port=5000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/commerce
spring.datasource.username=522649
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
