import type { ExperienceProfile } from "./experience-profile.types";

export const EXPERIENCE_RENDERER_VARIANTS: Record<string, string[]> = {
  "page.home": ["default"],
  "page.category-list": ["default"],
  "page.category-subcollections": ["default"],
  "page.category-products": ["default", "clp-list-v1", "clp-clearance-v1"],
  "page.product-detail": ["default"],
  "page.pdp-main": ["default"],
  "page.pdp-recommendations": ["default"],
  "page.pdp-reviews": ["default"],
  "page.pdp-faq": ["default"],
  "page.search-summary": ["default"],
  "page.search-products": ["default", "search-list-v1", "search-clearance-v1"],
  "page.search-results": ["default"],
  "page.content-page": ["default"],
  "page.cart": ["default"],
  "page.checkout-header": ["default"],
  "page.checkout-main": ["single-page", "multi-step", "express"],
  "page.checkout-summary": ["default"],
};

export const ALLOWED_THEME_KEYS = [
  "theme-default",
  "theme-green",
  "theme-orange",
] as const;

export const EXPERIENCE_PROFILES: ExperienceProfile[] = [
  {
    id: "exp-default-v1",
    storeKey: "*",
    routeKind: "*",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-default",
    slotRules: [],
  },
  {
    id: "exp-home-returning-v1",
    storeKey: "*",
    routeKind: "home",
    locale: "*",
    customerProfile: "returning",
    campaignKey: "*",
    layoutKey: "layout-default",
    slotRules: [],
    homeHero: {
      heading: "Welcome back to your garage",
      subheading: "Jump back into the parts and categories you shop most.",
      ctaLabel: "Shop best sellers",
      ctaUrl: "/categories",
    },
  },
  {
    id: "exp-checkout-returning-v1",
    storeKey: "*",
    routeKind: "checkout",
    locale: "*",
    customerProfile: "returning",
    campaignKey: "*",
    layoutKey: "layout-default",
    slotRules: [
      {
        rendererKey: "page.checkout-main",
        variantKey: "express",
      },
    ],
  },
  {
    id: "exp-store-a-v1",
    storeKey: "store-a",
    routeKind: "*",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-default",
    slotRules: [],
  },
  {
    id: "exp-store-b-v1",
    storeKey: "store-b",
    routeKind: "*",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-list-first",
    slotRules: [],
  },
  {
    id: "exp-store-c-v1",
    storeKey: "store-c",
    routeKind: "*",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-default",
    slotRules: [],
  },
  {
    id: "exp-store-b-category-es-v1",
    storeKey: "store-b",
    routeKind: "category-detail",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-list-first",
    slotRules: [
      {
        rendererKey: "page.category-products",
        variantKey: "clp-list-v1",
        layoutKey: "list",
        density: "comfortable",
      },
    ],
  },
  {
    id: "exp-store-b-search-es-v1",
    storeKey: "store-b",
    routeKind: "search",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-list-first",
    slotRules: [
      {
        rendererKey: "page.search-products",
        variantKey: "search-list-v1",
        layoutKey: "list",
        density: "comfortable",
      },
    ],
  },
  {
    id: "exp-store-b-product-es-v1",
    storeKey: "store-b",
    routeKind: "product-detail",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-list-first",
    slotRules: [
      {
        rendererKey: "page.pdp-faq",
        include: false,
      },
      {
        rendererKey: "page.pdp-recommendations",
        include: false,
      },
      {
        rendererKey: "page.pdp-reviews",
        include: false,
      },
    ],
  },
  {
    id: "exp-store-b-category-nl-v1",
    storeKey: "store-c",
    routeKind: "category-detail",
    locale: "*",
    customerProfile: "*",
    campaignKey: "*",
    layoutKey: "layout-list-first",
    slotRules: [
      {
        rendererKey: "page.category-products",
        variantKey: "clp-list-v1",
        layoutKey: "list",
        density: "comfortable",
      },
      {
        rendererKey: "page.pdp-reviews",
        include: false,
      },
    ],
  },
];
